version: '3'

services:
  app:
    image: 'minseokoh/coin:latest'
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATA_SOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create

  db:
    image: 'postgres:14.1-alpine'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=compose-postgres
