INSERT INTO question (id, type, question, option) VALUES (default, 'text', '자신의 MBTI는?', null);
INSERT INTO question (id, type, question, option) VALUES (default, 'text', '좋아하는 영화 장르는?', null);
INSERT INTO question (id, type, question, option) VALUES (default, 'text', '좋아하는 음악 장르는?', null);
INSERT INTO question (id, type, question, option) VALUES (default, 'text', '좋아하는 동물은?', null);
INSERT INTO question (id, type, question, option) VALUES (default, 'text', '무인도에 가져갈 하나의 물건은?', null);
INSERT INTO question (id, type, question, option) VALUES (default, 'text', '좋아하는 계절은?', null);
INSERT INTO question (id, type, question, option) VALUES (default, 'text', '학창시절 좋아했던 과목?', null);
INSERT INTO question (id, type, question, option) VALUES (default, 'text', '혈액형은?', null);
INSERT INTO question (id, type, question, option) VALUES (default, 'text', '여기서 옷 환불할 때 함께 가고 싶은 사람은?', null);
INSERT INTO question (id, type, question, option) VALUES (default, 'text', '카톡에 친구 제일 많을 것 같은 사람은?', null);
INSERT INTO question (id, type, question, option) VALUES (default, 'text', '어른들에게 가장 잘 할 것 같은 사람은?', null);

INSERT INTO question (id, type, question, option) VALUES (default, 'option', '시간 여행이 가능하다면', '{"과거", "미래"}');
INSERT INTO question (id, type, question, option) VALUES (default, 'option', '쉴 때', '{"집 안", "집 밖"}');
INSERT INTO question (id, type, question, option) VALUES (default, 'option', '둘 중 나은 것은', '{"토맛 토마토", "토마토맛 토"}');
INSERT INTO question (id, type, question, option) VALUES (default, 'option', '둘 중 좋은 것은', '{"국내 여행", "해외 여행"}');
INSERT INTO question (id, type, question, option) VALUES (default, 'option', '여행을 할 때', '{"휴양형", "활동형"}');
INSERT INTO question (id, type, question, option) VALUES (default, 'option', '둘 중 나은 것은', '{"양치 못하기", "샤워 못하기"}');
INSERT INTO question (id, type, question, option) VALUES (default, 'option', '둘 중 좋은 것은', '{"아이폰", "갤럭시"}');
INSERT INTO question (id, type, question, option) VALUES (default, 'option', '둘 중 나은 것은', '{"잠수 이별", "환승 이별"}');
INSERT INTO question (id, type, question, option) VALUES (default, 'option', '사람은 본질적으로', '{"이타적", "이기적"}');
INSERT INTO question (id, type, question, option) VALUES (default, 'option', '둘 중 어떤 것이 먼저일까', '{"닭", "계란"}');
INSERT INTO question (id, type, question, option) VALUES (default, 'option', '셋 중 좋은 것은', '{"연하", "동갑", "연상"}');
INSERT INTO question (id, type, question, option) VALUES (default, 'option', '1억을 한 번에 써야 한다면', '{"로또 사기", "국내 여행 가기"}');
INSERT INTO question (id, type, question, option) VALUES (default, 'option', '둘 중 좋은 것은', '{"전화", "문자"}');
INSERT INTO question (id, type, question, option) VALUES (default, 'option', '선의의 거짓말', '{"괜찮다", "아니다"}');
INSERT INTO question (id, type, question, option) VALUES (default, 'option', '둘 중 좋아하는 동물은', '{"강아지", "고양이"}');
INSERT INTO question (id, type, question, option) VALUES (default, 'option', '핫도그는 샌드위치다', '{"맞다", "아니다"}');
INSERT INTO question (id, type, question, option) VALUES (default, 'option', '셋 중 좋은 것은', '{"부먹", "찍먹", "처먹"}');